---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
    
---
spring:
  config.activate.on-profile: testUsers
cds:
  security:
    mock.users:
    - name: guest
      password: 1
      roles:
      - GuestUser
    - name: priv
      password: 2
      roles:
      - PrivilegedUser